// TODO https://www.openarchives.org/OAI/2.0/branding.xsd
// TODO https://www.openarchives.org/OAI/2.0/guidelines-branding.htm

// This file was generated by the Eclipse Implementation of JAXB, v4.0.6 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//


package org.openarchives.oai._2_0.branding;

import java.util.ArrayList;
import java.util.List;
import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlRootElement;
import jakarta.xml.bind.annotation.XmlType;


/**
 * &lt;p&gt;Java class for anonymous complex type&lt;/p&gt;.
 * 
 * &lt;p&gt;The following schema fragment specifies the expected content contained within this class.&lt;/p&gt;
 * 
 * &lt;pre&gt;{&#064;code
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="collectionIcon" type="{http://www.openarchives.org/OAI/2.0/branding/}collectionIconType" minOccurs="0"/&gt;
 *         &lt;element name="metadataRendering" type="{http://www.openarchives.org/OAI/2.0/branding/}metadataRenderingType" maxOccurs="unbounded" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * }&lt;/pre&gt;
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "collectionIcon",
    "metadataRendering"
})
@XmlRootElement(name = "branding")
public class Branding {

    protected CollectionIconType collectionIcon;
    protected List<MetadataRenderingType> metadataRendering;

    /**
     * Gets the value of the collectionIcon property.
     * 
     * @return
     *     possible object is
     *     {@link CollectionIconType }
     *     
     */
    public CollectionIconType getCollectionIcon() {
        return collectionIcon;
    }

    /**
     * Sets the value of the collectionIcon property.
     * 
     * @param value
     *     allowed object is
     *     {@link CollectionIconType }
     *     
     */
    public void setCollectionIcon(CollectionIconType value) {
        this.collectionIcon = value;
    }

    /**
     * Gets the value of the metadataRendering property.
     * 
     * <p>This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the Jakarta XML Binding object.
     * This is why there is not a {@code set} method for the metadataRendering property.</p>
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * </p>
     * <pre>
     * getMetadataRendering().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link MetadataRenderingType }
     * </p>
     * 
     * 
     * @return
     *     The value of the metadataRendering property.
     */
    public List<MetadataRenderingType> getMetadataRendering() {
        if (metadataRendering == null) {
            metadataRendering = new ArrayList<>();
        }
        return this.metadataRendering;
    }

}
