//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.6 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//


package org.openarchives.oai._2_0.branding;

import jakarta.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the org.openarchives.oai._2_0.branding package. 
 * <p>An ObjectFactory allows you to programmatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: org.openarchives.oai._2_0.branding
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Branding }
     * 
     * @return
     *     the new instance of {@link Branding }
     */
    public Branding createBranding() {
        return new Branding();
    }

    /**
     * Create an instance of {@link CollectionIconType }
     * 
     * @return
     *     the new instance of {@link CollectionIconType }
     */
    public CollectionIconType createCollectionIconType() {
        return new CollectionIconType();
    }

    /**
     * Create an instance of {@link MetadataRenderingType }
     * 
     * @return
     *     the new instance of {@link MetadataRenderingType }
     */
    public MetadataRenderingType createMetadataRenderingType() {
        return new MetadataRenderingType();
    }

}
