name: nefeli
services:
  web:
    build:
      context: ./nefeli-web/
      dockerfile: ./src/main/docker/Dockerfile
    image: nefeli-web:1.0.0-SNAPSHOT
    container_name: nefeli-web
    ports:
      - "8080:8080"
      - "5000:5000"
    depends_on:
      - db
  db:
    build:
      context: ./nefeli-db/
      dockerfile: ./src/main/docker/Dockerfile
    image: nefeli-db:1.0.0-SNAPSHOT
    container_name: nefeli-db
    ports:
      - "5432:5432"
