CREATE TABLE IF NOT EXISTS "REPOSITORY"("URL" VARCHAR PRIMARY KEY, "UPDATED" TIMESTAMP WITH TIME ZONE, "NAME" VARCHAR, "EARLIEST" TIMESTAMP WITH TIME ZONE, "DELETED" INTEGER, "GRANULARITY" INTEGER);
CREATE TABLE IF NOT EXISTS "REPOSITORY_ADMINS"("URL" VARCHAR NOT NULL, "ADMIN" VARCHAR NOT NULL, PRIMARY KEY ("URL", "ADMIN"), FOREIGN KEY ("URL") REFERENCES "REPOSITORY"("URL") ON DELETE CASCADE);
