nefeli.db.jdbc.driver = org.postgresql.Driver
nefeli.db.jdbc.url = jdbc:postgresql://host.docker.internal:5432/nefeli
nefeli.db.jdbc.user = nefeli
nefeli.db.jdbc.password = n3f3l1
nefeli.harvester.period = P1D
nefeli.harvester.threads = 10
nefeli.harvester.batch = 100
