//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.6 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//

// TODO https://www.openarchives.org/OAI/1.1/eprints.xsd
// TODO https://www.openarchives.org/OAI/2.0/guidelines-eprints.htm

package org.openarchives.oai._1_1.eprints;

import java.util.ArrayList;
import java.util.List;
import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlType;


/**
 * &lt;p&gt;Java class for eprintsDescriptionType complex type&lt;/p&gt;.
 * 
 * &lt;p&gt;The following schema fragment specifies the expected content contained within this class.&lt;/p&gt;
 * 
 * &lt;pre&gt;{&#064;code
 * &lt;complexType name="eprintsDescriptionType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="content" type="{http://www.openarchives.org/OAI/1.1/eprints}TextURLType" minOccurs="0"/&gt;
 *         &lt;element name="metadataPolicy" type="{http://www.openarchives.org/OAI/1.1/eprints}TextURLType"/&gt;
 *         &lt;element name="dataPolicy" type="{http://www.openarchives.org/OAI/1.1/eprints}TextURLType"/&gt;
 *         &lt;element name="submissionPolicy" type="{http://www.openarchives.org/OAI/1.1/eprints}TextURLType" minOccurs="0"/&gt;
 *         &lt;element name="comment" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * }&lt;/pre&gt;
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "eprintsDescriptionType", propOrder = {
    "content",
    "metadataPolicy",
    "dataPolicy",
    "submissionPolicy",
    "comment"
})
public class EprintsDescriptionType {

    protected TextURLType content;
    @XmlElement(required = true)
    protected TextURLType metadataPolicy;
    @XmlElement(required = true)
    protected TextURLType dataPolicy;
    protected TextURLType submissionPolicy;
    protected List<String> comment;

    /**
     * Gets the value of the content property.
     * 
     * @return
     *     possible object is
     *     {@link TextURLType }
     *     
     */
    public TextURLType getContent() {
        return content;
    }

    /**
     * Sets the value of the content property.
     * 
     * @param value
     *     allowed object is
     *     {@link TextURLType }
     *     
     */
    public void setContent(TextURLType value) {
        this.content = value;
    }

    /**
     * Gets the value of the metadataPolicy property.
     * 
     * @return
     *     possible object is
     *     {@link TextURLType }
     *     
     */
    public TextURLType getMetadataPolicy() {
        return metadataPolicy;
    }

    /**
     * Sets the value of the metadataPolicy property.
     * 
     * @param value
     *     allowed object is
     *     {@link TextURLType }
     *     
     */
    public void setMetadataPolicy(TextURLType value) {
        this.metadataPolicy = value;
    }

    /**
     * Gets the value of the dataPolicy property.
     * 
     * @return
     *     possible object is
     *     {@link TextURLType }
     *     
     */
    public TextURLType getDataPolicy() {
        return dataPolicy;
    }

    /**
     * Sets the value of the dataPolicy property.
     * 
     * @param value
     *     allowed object is
     *     {@link TextURLType }
     *     
     */
    public void setDataPolicy(TextURLType value) {
        this.dataPolicy = value;
    }

    /**
     * Gets the value of the submissionPolicy property.
     * 
     * @return
     *     possible object is
     *     {@link TextURLType }
     *     
     */
    public TextURLType getSubmissionPolicy() {
        return submissionPolicy;
    }

    /**
     * Sets the value of the submissionPolicy property.
     * 
     * @param value
     *     allowed object is
     *     {@link TextURLType }
     *     
     */
    public void setSubmissionPolicy(TextURLType value) {
        this.submissionPolicy = value;
    }

    /**
     * Gets the value of the comment property.
     * 
     * <p>This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the Jakarta XML Binding object.
     * This is why there is not a {@code set} method for the comment property.</p>
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * </p>
     * <pre>
     * getComment().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link String }
     * </p>
     * 
     * 
     * @return
     *     The value of the comment property.
     */
    public List<String> getComment() {
        if (comment == null) {
            comment = new ArrayList<>();
        }
        return this.comment;
    }

}
