//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.6 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//


package org.openarchives.oai._1_1.eprints;

import javax.xml.namespace.QName;
import jakarta.xml.bind.JAXBElement;
import jakarta.xml.bind.annotation.XmlElementDecl;
import jakarta.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the org.openarchives.oai._1_1.eprints package. 
 * <p>An ObjectFactory allows you to programmatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private static final QName _Eprints_QNAME = new QName("http://www.openarchives.org/OAI/1.1/eprints", "eprints");
    private static final QName _TextURLTypeURL_QNAME = new QName("http://www.openarchives.org/OAI/1.1/eprints", "URL");
    private static final QName _TextURLTypeText_QNAME = new QName("http://www.openarchives.org/OAI/1.1/eprints", "text");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: org.openarchives.oai._1_1.eprints
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link EprintsDescriptionType }
     * 
     * @return
     *     the new instance of {@link EprintsDescriptionType }
     */
    public EprintsDescriptionType createEprintsDescriptionType() {
        return new EprintsDescriptionType();
    }

    /**
     * Create an instance of {@link TextURLType }
     * 
     * @return
     *     the new instance of {@link TextURLType }
     */
    public TextURLType createTextURLType() {
        return new TextURLType();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link EprintsDescriptionType }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link EprintsDescriptionType }{@code >}
     */
    @XmlElementDecl(namespace = "http://www.openarchives.org/OAI/1.1/eprints", name = "eprints")
    public JAXBElement<EprintsDescriptionType> createEprints(EprintsDescriptionType value) {
        return new JAXBElement<>(_Eprints_QNAME, EprintsDescriptionType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    @XmlElementDecl(namespace = "http://www.openarchives.org/OAI/1.1/eprints", name = "URL", scope = TextURLType.class)
    public JAXBElement<String> createTextURLTypeURL(String value) {
        return new JAXBElement<>(_TextURLTypeURL_QNAME, String.class, TextURLType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    @XmlElementDecl(namespace = "http://www.openarchives.org/OAI/1.1/eprints", name = "text", scope = TextURLType.class)
    public JAXBElement<String> createTextURLTypeText(String value) {
        return new JAXBElement<>(_TextURLTypeText_QNAME, String.class, TextURLType.class, value);
    }

}
