//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.6 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//


package org.openarchives.oai._2_0.rights;

import javax.xml.namespace.QName;
import jakarta.xml.bind.JAXBElement;
import jakarta.xml.bind.annotation.XmlElementDecl;
import jakarta.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the org.openarchives.oai._2_0.rights package. 
 * <p>An ObjectFactory allows you to programmatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private static final QName _Rights_QNAME = new QName("http://www.openarchives.org/OAI/2.0/rights/", "rights");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: org.openarchives.oai._2_0.rights
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link RightsStatementType }
     * 
     * @return
     *     the new instance of {@link RightsStatementType }
     */
    public RightsStatementType createRightsStatementType() {
        return new RightsStatementType();
    }

    /**
     * Create an instance of {@link RightsStatementType.RightsReference }
     * 
     * @return
     *     the new instance of {@link RightsStatementType.RightsReference }
     */
    public RightsStatementType.RightsReference createRightsStatementTypeRightsReference() {
        return new RightsStatementType.RightsReference();
    }

    /**
     * Create an instance of {@link RightsStatementType.RightsDefinition }
     * 
     * @return
     *     the new instance of {@link RightsStatementType.RightsDefinition }
     */
    public RightsStatementType.RightsDefinition createRightsStatementTypeRightsDefinition() {
        return new RightsStatementType.RightsDefinition();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link RightsStatementType }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link RightsStatementType }{@code >}
     */
    @XmlElementDecl(namespace = "http://www.openarchives.org/OAI/2.0/rights/", name = "rights")
    public JAXBElement<RightsStatementType> createRights(RightsStatementType value) {
        return new JAXBElement<>(_Rights_QNAME, RightsStatementType.class, null, value);
    }

}
