//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.6 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//


package org.openarchives.oai._2_0.friends;

import javax.xml.namespace.QName;
import jakarta.xml.bind.JAXBElement;
import jakarta.xml.bind.annotation.XmlElementDecl;
import jakarta.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the org.openarchives.oai._2_0.friends package. 
 * <p>An ObjectFactory allows you to programmatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private static final QName _Friends_QNAME = new QName("http://www.openarchives.org/OAI/2.0/friends/", "friends");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: org.openarchives.oai._2_0.friends
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link FriendsType }
     * 
     * @return
     *     the new instance of {@link FriendsType }
     */
    public FriendsType createFriendsType() {
        return new FriendsType();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link FriendsType }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link FriendsType }{@code >}
     */
    @XmlElementDecl(namespace = "http://www.openarchives.org/OAI/2.0/friends/", name = "friends")
    public JAXBElement<FriendsType> createFriends(FriendsType value) {
        return new JAXBElement<>(_Friends_QNAME, FriendsType.class, null, value);
    }

}
