//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.6 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//


package org.openarchives.oai._2_0.gateway;

import java.util.ArrayList;
import java.util.List;
import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlRootElement;
import jakarta.xml.bind.annotation.XmlSchemaType;
import jakarta.xml.bind.annotation.XmlType;

// TODO https://www.openarchives.org/OAI/2.0/gateway.xsd
// TODO https://www.openarchives.org/OAI/2.0/guidelines-gateway.htm

/**
 * &lt;p&gt;Java class for anonymous complex type&lt;/p&gt;.
 * 
 * &lt;p&gt;The following schema fragment specifies the expected content contained within this class.&lt;/p&gt;
 * 
 * &lt;pre&gt;{&#064;code
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="source" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="gatewayDescription" type="{http://www.w3.org/2001/XMLSchema}anyURI"/&gt;
 *         &lt;element name="gatewayAdmin" type="{http://www.openarchives.org/OAI/2.0/}emailType" maxOccurs="unbounded"/&gt;
 *         &lt;element name="gatewayURL" type="{http://www.w3.org/2001/XMLSchema}anyURI" minOccurs="0"/&gt;
 *         &lt;element name="gatewayNotes" type="{http://www.w3.org/2001/XMLSchema}anyURI" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * }&lt;/pre&gt;
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "source",
    "gatewayDescription",
    "gatewayAdmin",
    "gatewayURL",
    "gatewayNotes"
})
@XmlRootElement(name = "gateway")
public class Gateway {

    @XmlElement(required = true)
    protected String source;
    @XmlElement(required = true)
    @XmlSchemaType(name = "anyURI")
    protected String gatewayDescription;
    @XmlElement(required = true)
    protected List<String> gatewayAdmin;
    @XmlSchemaType(name = "anyURI")
    protected String gatewayURL;
    @XmlSchemaType(name = "anyURI")
    protected String gatewayNotes;

    /**
     * Gets the value of the source property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSource() {
        return source;
    }

    /**
     * Sets the value of the source property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSource(String value) {
        this.source = value;
    }

    /**
     * Gets the value of the gatewayDescription property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getGatewayDescription() {
        return gatewayDescription;
    }

    /**
     * Sets the value of the gatewayDescription property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setGatewayDescription(String value) {
        this.gatewayDescription = value;
    }

    /**
     * Gets the value of the gatewayAdmin property.
     * 
     * <p>This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the Jakarta XML Binding object.
     * This is why there is not a {@code set} method for the gatewayAdmin property.</p>
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * </p>
     * <pre>
     * getGatewayAdmin().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link String }
     * </p>
     * 
     * 
     * @return
     *     The value of the gatewayAdmin property.
     */
    public List<String> getGatewayAdmin() {
        if (gatewayAdmin == null) {
            gatewayAdmin = new ArrayList<>();
        }
        return this.gatewayAdmin;
    }

    /**
     * Gets the value of the gatewayURL property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getGatewayURL() {
        return gatewayURL;
    }

    /**
     * Sets the value of the gatewayURL property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setGatewayURL(String value) {
        this.gatewayURL = value;
    }

    /**
     * Gets the value of the gatewayNotes property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getGatewayNotes() {
        return gatewayNotes;
    }

    /**
     * Sets the value of the gatewayNotes property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setGatewayNotes(String value) {
        this.gatewayNotes = value;
    }

}
